FROM python3.12-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in package.json
RUN pip install -r requirements.txt

# Make port 3000 available to the world outside this container
EXPOSE 9669

# Run the app when the container launches
CMD ["python", "app.py"]